### ISSUE TITLE
Failed to typecheck

### ISSUE THREAD

**Issue by ice1000** [gallais/thesis#1]
in generic-syntax.agda/Generic/Fusion/Syntactic.lagda

Agda gives this error:

```
((Γ ─Env) Var Δ) !=< (List _I_219) of type Set
when checking that the expression Θ has type List _I_219
```

I'm quite confused about this, I don't know how to fix it.
Can you help me?

(Or provide a release build will be fine, I just want to read it)

**Comment by gallais** [comment]
I can't reproduce the bug. But I have updated the code to work with the current Agda dev and the current agda-stdlib dev (experimental branch).

**Comment by ice1000** [comment]
Thank you!
